apiVersion: batch/v1
kind: Job
metadata:
  name: docker-build
spec:
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
        - name: docker-daemon
          image: docker:20-dind
          securityContext:
            privileged: true
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker
            - name: dind-certs
              mountPath: /certs
            - name: registry-cert
              mountPath: /etc/docker/certs.d/registry.default
          env:
          - name: DOCKER_TLS_CERTDIR
            value: /certs
        - name: docker
          image: docker:20
          command: ["/bin/sh", "-c", "sleep 5 && docker build -t registry.default/mssql-2017:latest /files && docker push registry.default/mssql-2017:latest"]
          env:
          - name: DOCKER_HOST
            value: tcp://localhost:2376
          - name: DOCKER_TLS_CERTDIR
            value: /certs
          - name: DOCKER_TLS_VERIFY
            value: "1"
          - name: DOCKER_CERT_PATH
            value: /certs/client
          volumeMounts:
            - name: dind-certs
              mountPath: /certs
            - name: registry-cert
              mountPath: /etc/docker/certs.d/registry.default
            - name: files
              mountPath: /files
      restartPolicy: Never
      volumes:
      - name: dind-storage
        emptyDir: {}
      - name: dind-certs
        emptyDir: {}
      - name: registry-cert
        persistentVolumeClaim:
          claimName: registry-cert
      - name: files
        configMap:
          name: config
          defaultMode: 0777
