apiVersion: batch/v1
kind: Job
metadata:
  name: pod
spec:
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
        - name: dind
          image: docker:20-dind
          securityContext:
            privileged: true
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker
            - name: dind-certs
              mountPath: /certs
            - name: registry-cert
              mountPath: /etc/docker/certs.d/registry.default
          env:
          - name: DOCKER_TLS_CERTDIR
            value: /certs
        - name: my-main-container
          image: docker:20
          command: ["/bin/sh", "-c", "sleep 10000"]
          env:
          - name: DOCKER_HOST
            value: tcp://localhost:2376
          - name: DOCKER_TLS_CERTDIR
            value: /certs
          - name: DOCKER_TLS_VERIFY
            value: "1"
          - name: DOCKER_CERT_PATH
            value: /certs/client
          volumeMounts:
            - name: dind-certs
              mountPath: /certs
            - name: registry-cert
              mountPath: /etc/docker/certs.d/registry.default
      restartPolicy: Never
      volumes:
      - name: dind-storage
        emptyDir: {}
      - name: dind-certs
        emptyDir: {}
      - name: registry-cert
        persistentVolumeClaim:
          claimName: registry-cert
