apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: foo
        image: localhost:30007/wibble
        command: ["/bin/sh", "-c", "sleep 10000"]