apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: foo
spec:
  containers:
    - name: foo
      image: localhost:30007/mssql-2017:latest
      env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: Peruzzi1