apiVersion: batch/v1
kind: Job
metadata:
  name: docker-build
spec:
  template:
    metadata:
      labels:
        app: docker
    spec:
      initContainers:
        - name: create-lockfile
          image: busybox
          command: ['sh', '-c', 'touch /liveness/job.live']
          volumeMounts:
            - name: liveness
              mountPath: /liveness
      containers:
        - name: docker-daemon
          image: docker:20-dind
          securityContext:
            privileged: true
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker
            - name: dind-certs
              mountPath: /certs
            - name: registry-cert
              mountPath: /etc/docker/certs.d/registry.default
            - name: liveness
              mountPath: /liveness
          env:
          - name: DOCKER_TLS_CERTDIR
            value: /certs
          livenessProbe:
            exec:
              command:
                - stat 
                - /liveness/job.live
        - name: docker
          image: docker:20
          command: ["/bin/sh", "-c", "sleep 5 && docker build -t registry.default/helloworld:latest /files && docker push registry.default/helloworld:latest && rm /liveness/job.live"]
          env:
          - name: DOCKER_HOST
            value: tcp://localhost:2376
          - name: DOCKER_TLS_CERTDIR
            value: /certs
          - name: DOCKER_TLS_VERIFY
            value: "1"
          - name: DOCKER_CERT_PATH
            value: /certs/client
          volumeMounts:
            - name: dind-certs
              mountPath: /certs
            - name: registry-cert
              mountPath: /etc/docker/certs.d/registry.default
            - name: files
              mountPath: /files
            - name: liveness
              mountPath: /liveness
      restartPolicy: Never
      volumes:
      - name: dind-storage
        emptyDir: {}
      - name: dind-certs
        emptyDir: {}
      - name: liveness
        emptyDir: {}
      - name: registry-cert
        persistentVolumeClaim:
          claimName: registry-cert
      - name: files
        configMap:
          name: my-config
          defaultMode: 0777
