apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: NodePort
  selector:
    app: registry
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: registry
    nodePort: 30007
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: registry-cert
spec:
    accessModes:
      - ReadWriteMany
    storageClassName: standard
    resources:
        requests:
            storage: 10Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      initContainers:
      - name: configure-tls
        image: alpine/openssl
        command: ['sh', '-c', 'apk add --update openssl && openssl req -newkey rsa:4096 -nodes -sha256 -keyout certs/domain.key -addext "subjectAltName = DNS:registry.default" -x509 -days 365 -out certs/domain.crt -subj "/C=GB/ST=Cambridgeshire/L=Cambridge/O=Red Gate Software Ltd./CN=registry.default" && cp certs/domain.crt registrycert/ca.crt']
        volumeMounts:
        - name: certs
          mountPath: /certs
        - name: registry-cert
          mountPath: /registrycert
      containers:
      - name: registry
        image: registry:2
        env:
          - name: REGISTRY_AUTH
            value: none
          - name: REGISTRY_HTTP_ADDR
            value: 0.0.0.0:443
          - name: REGISTRY_HTTP_TLS_CERTIFICATE
            value: /certs/domain.crt
          - name: REGISTRY_HTTP_TLS_KEY
            value: /certs/domain.key
        volumeMounts:
        - name: certs
          mountPath: /certs
      volumes:
      - name: registry-cert
        persistentVolumeClaim:
          claimName: registry-cert
      - name: certs
        emptyDir: {}
